[buildPlans.iosevka3]
family = "iosevka3"
spacing = "term"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false
no-ligation = true

[buildPlans.iosevka3.variants.design]
capital-a = "straight-serifless"
capital-b = "more-asymmetric-serifless"
capital-c = "serifless"
capital-d = "more-rounded-serifless"
capital-e = "serifless"
capital-f = "serifless"
capital-g = "toothless-rounded-serifless-hooked"
capital-h = "serifless"
capital-i = "serifed"
capital-j = "descending-serifed"
capital-k = "straight-serifless"
capital-l = "serifless"
capital-m = "hanging"
capital-n = "standard"
capital-p = "closed"
capital-q = "crossing"
capital-r = "straight"
capital-s = "serifless"
capital-t = "serifless"
capital-u = "toothed"
capital-v = "straight"
capital-w = "straight-vertical-sides"
capital-x = "straight-serifless"
capital-y = "straight-serifless"
capital-z = "straight-serifless"
a = "double-storey-serifless"
b = "toothed"
c = "serifless"
d = "toothed-serifless"
e = "flat-crossbar"
f = "extended"
g = "single-storey-serifless"
h = "straight"
i = "serifed"
j = "serifed"
k = "straight-serifless"
l = "serifed"
m = "normal"
n = "straight"
p = "eared"
q = "straight"
r = "serifless"
s = "serifless"
t = "standard"
u = "toothed"
v = "straight"
w = "straight-vertical-sides"
x = "straight-serifless"
y = "straight"
z = "straight-serifless"
zero = "slashed"
one = "base"
two = "straight-neck"
three = "two-arcs"
four = "semi-open"
five = "vertical-upper-left-bar"
six = "straight-bar"
seven = "straight-serifless"
eight = "crossing"
nine = "straight-bar"
punctuation-dot = "round"
tilde = "high"
asterisk = "penta-high"
underscore = "high"
caret = "high"
paren = "normal"
brace = "straight"
number-sign = "upright"
ampersand = "closed"
at = "threefold"
dollar = "through"
percent = "rings-segmented-slash"
bar = "natural-slope"
ascii-single-quote = "straight"
ascii-grave = "straight"
question = "smooth"

[buildPlans.iosevka3.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka3.weights.bold]
shape = 700
menu = 700
css = 700
